#!/usr/bin/env bash

# Sourced by the build_ffmpeg_*.sh scripts. Trims FFmpeg down to what playing
# audio needs, since Songo never decodes video or images (tags and cover art
# are read by a separate library). The video, subtitle and image decoders were
# three quarters of the binary.
#
# Everything not listed here stays at FFmpeg's defaults: demuxers other than
# the image ones (any container can carry audio, and embedded cover art is
# read inside the audio demuxers), bitstream filters and protocols, so network
# playback behaves the same as a full build.
#
# All three lists were made for FFmpeg n8.1.2. Revisit them when updating
# FFmpeg, as new components won't be built until they're added here.

# Decoders: every built-in audio decoder. From libavcodec/allcodecs.c,
# everything between the "audio codecs" and "subtitles" comments (audio, PCM,
# DPCM, ADPCM), minus hdr (an image codec filed there), plus comfortnoise,
# dvaudio, eightsvx_exp, eightsvx_fib, rka, s302m and speex (audio codecs filed
# with the video ones). Checked against a full build, where these are exactly
# the decoders reporting AVMEDIA_TYPE_AUDIO (apart from anull, a placeholder).
FFMPEG_AUDIO_DECODERS="$(tr '\n' ',' <<'LIST'
aac
aac_fixed
aac_latm
ac3
ac3_fixed
acelp_kelvin
adpcm_4xm
adpcm_adx
adpcm_afc
adpcm_agm
adpcm_aica
adpcm_argo
adpcm_circus
adpcm_ct
adpcm_dtk
adpcm_ea
adpcm_ea_maxis_xa
adpcm_ea_r1
adpcm_ea_r2
adpcm_ea_r3
adpcm_ea_xas
adpcm_g722
adpcm_g726
adpcm_g726le
adpcm_ima_acorn
adpcm_ima_alp
adpcm_ima_amv
adpcm_ima_apc
adpcm_ima_apm
adpcm_ima_cunning
adpcm_ima_dat4
adpcm_ima_dk3
adpcm_ima_dk4
adpcm_ima_ea_eacs
adpcm_ima_ea_sead
adpcm_ima_escape
adpcm_ima_hvqm2
adpcm_ima_hvqm4
adpcm_ima_iss
adpcm_ima_magix
adpcm_ima_moflex
adpcm_ima_mtf
adpcm_ima_oki
adpcm_ima_pda
adpcm_ima_qt
adpcm_ima_rad
adpcm_ima_smjpeg
adpcm_ima_ssi
adpcm_ima_wav
adpcm_ima_ws
adpcm_ima_xbox
adpcm_ms
adpcm_mtaf
adpcm_n64
adpcm_psx
adpcm_psxc
adpcm_sanyo
adpcm_sbpro_2
adpcm_sbpro_3
adpcm_sbpro_4
adpcm_swf
adpcm_thp
adpcm_thp_le
adpcm_vima
adpcm_xa
adpcm_xmd
adpcm_yamaha
adpcm_zork
ahx
alac
als
amrnb
amrwb
apac
ape
aptx
aptx_hd
atrac1
atrac3
atrac3al
atrac3p
atrac3pal
atrac9
binkaudio_dct
binkaudio_rdft
bmv_audio
bonk
cbd2_dpcm
comfortnoise
cook
dca
derf_dpcm
dfpwm
dolby_e
dsd_lsbf
dsd_lsbf_planar
dsd_msbf
dsd_msbf_planar
dsicinaudio
dss_sp
dst
dvaudio
eac3
eightsvx_exp
eightsvx_fib
evrc
fastaudio
ffwavesynth
flac
ftr
g723_1
g728
g729
gremlin_dpcm
gsm
gsm_ms
hca
hcom
iac
ilbc
imc
interplay_acm
interplay_dpcm
mace3
mace6
metasound
misc4
mlp
mp1
mp1float
mp2
mp2float
mp3
mp3adu
mp3adufloat
mp3float
mp3on4
mp3on4float
mpc7
mpc8
msnsiren
nellymoser
on2avc
opus
osq
paf_audio
pcm_alaw
pcm_bluray
pcm_dvd
pcm_f16le
pcm_f24le
pcm_f32be
pcm_f32le
pcm_f64be
pcm_f64le
pcm_lxf
pcm_mulaw
pcm_s16be
pcm_s16be_planar
pcm_s16le
pcm_s16le_planar
pcm_s24be
pcm_s24daud
pcm_s24le
pcm_s24le_planar
pcm_s32be
pcm_s32le
pcm_s32le_planar
pcm_s64be
pcm_s64le
pcm_s8
pcm_s8_planar
pcm_sga
pcm_u16be
pcm_u16le
pcm_u24be
pcm_u24le
pcm_u32be
pcm_u32le
pcm_u8
pcm_vidc
qcelp
qdm2
qdmc
qoa
ra_144
ra_288
ralf
rka
roq_dpcm
s302m
sbc
sdx2_dpcm
shorten
sipr
siren
smackaud
sol_dpcm
sonic
speex
tak
truehd
truespeech
tta
twinvq
vmdaudio
vorbis
wady_dpcm
wavarc
wavpack
wmalossless
wmapro
wmav1
wmav2
wmavoice
ws_snd1
xan_dpcm
xma1
xma2
LIST
)"
FFMPEG_AUDIO_DECODERS="${FFMPEG_AUDIO_DECODERS%,}"

# Parsers: only the audio ones, by their libavcodec/parsers.c names. Checked
# against a full build, where these are exactly the parsers whose codecs are
# AVMEDIA_TYPE_AUDIO. Cover art arrives as one whole packet, so it never needs
# the image parsers.
FFMPEG_AUDIO_PARSERS="$(tr '\n' ',' <<'LIST'
aac
aac_latm
ac3
adx
amr
cook
dolby_e
dca
dvaudio
flac
ftr
g723_1
g729
gsm
misc4
mlp
mpegaudio
opus
sbc
sipr
tak
vorbis
xma
LIST
)"
FFMPEG_AUDIO_PARSERS="${FFMPEG_AUDIO_PARSERS%,}"

# Demuxers turned off: the image ones from libavformat/allformats.c, which only
# open image files and image sequences as video.
FFMPEG_IMAGE_DEMUXERS="$(tr '\n' ',' <<'LIST'
image2
image2_alias_pix
image2_brender_pix
image2pipe
image_bmp_pipe
image_cri_pipe
image_dds_pipe
image_dpx_pipe
image_exr_pipe
image_gem_pipe
image_gif_pipe
image_hdr_pipe
image_j2k_pipe
image_jpeg_pipe
image_jpegls_pipe
image_jpegxl_pipe
image_jpegxs_pipe
image_pam_pipe
image_pbm_pipe
image_pcx_pipe
image_pfm_pipe
image_pgm_pipe
image_pgmyuv_pipe
image_pgx_pipe
image_phm_pipe
image_photocd_pipe
image_pictor_pipe
image_png_pipe
image_ppm_pipe
image_psd_pipe
image_qdraw_pipe
image_qoi_pipe
image_sgi_pipe
image_sunrast_pipe
image_svg_pipe
image_tiff_pipe
image_vbn_pipe
image_webp_pipe
image_xbm_pipe
image_xpm_pipe
image_xwd_pipe
LIST
)"
FFMPEG_IMAGE_DEMUXERS="${FFMPEG_IMAGE_DEMUXERS%,}"
